### ISSUE TITLE
vst3 keeps going dry in Reaper

### ISSUE THREAD

**Issue by sirjohndfox** [brummer10/guitarix.vst#25]
Gday I've got a problem where guitarix will stop sounding it's effects in reaper.  

The meters in the plugin gui still move but it is only dry signal coming through. 

Off-lining them and re-enable will work but then after a few transport starts and stops there is only dry signal again.

Any idea where I could look for more info?  Tried running from terminal, but doesn't appear to be any useful info.

Last test with Reaper 7.15 and Guitarix.vst3 0.3.

Very frustrating bug.

**Comment by brummer10** [comment]
Can't say exactly, but, do you use a convolver (Ir-file loader presence or cabinet)? And if so, did that happen as well if you disable them?

**Comment by sirjohndfox** [comment]
From a cursory trial it seems disabling the convolver solves it.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by sirjohndfox** [comment]
this is on linux btw.

**Comment by brummer10** [comment]
Okay, then I guess I know how to solve that. Just I'm away for two weeks now. I'll write a notice here when done.

**Comment by sirjohndfox** [comment]
no worries, take your time.
Thanks

**Comment by brummer10** [comment]
So I've pushed a fix for this to the repository. Let me know please if it fix the issue for you as well.

**Comment by johnny2k** [comment]
Same issue for me here as well.

Updated to the latest plugin release (d3b47ee2a31a66f8e64004a5a76df32ec26302a3), rebuilt and installed. In latest Reaper (v7.16) I get the dry signal after selecting a preset that uses an enabled convolver. Functionality can be restored if using the steps suggested before.

Let me know if there's anything else I can do to help.

```
➜  guitarix.vst git:(main) ✗ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
➜  guitarix.vst git:(main) ✗ uname -a      
Linux johnny-Z87X-HD3 5.15.0-91-lowlatency #101-Ubuntu SMP PREEMPT Thu Nov 16 14:17:44 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sirjohndfox** [comment]
I just tried the binary. Unfortunately the problem persists.  My initial reaction is that it is happening less.  Unfortunately I can't *make* it happen.

**Comment by brummer10** [comment]
Okay, now it should be really fixed.

**Comment by sirjohndfox** [comment]
Looks to have done the trick. Thank you!
