### ISSUE TITLE
A cabinet type change doesn't take effect until the cabinet simulator is reloaded

### ISSUE THREAD

**Issue by Gimmeapill** [brummer10/guitarix.vst#7]
A change of cabinet doesn't take effect immediately: the cabinet module needs to be deactivated/reactivated for the change to be applied. This looks like a defect compared to the behavior of Guitarix standalone.

**Comment by brummer10** [comment]
Strange, I can't reproduce this one. Does it as well happen in Carla?

**Comment by Gimmeapill** [comment]
It does. I tried also in Renoise & with Carla, the behavior is the same: a cabinet type change has no effect until the module is muted/unmuted, then the change takes effect

**Comment by kramlie** [comment]
I can reproduce this as well.

**Comment by kramlie** [comment]
Btw, I just noticed that this also happens with the Presence knob on the Amp Stack. You have to turn Presence off and on again for the knob to have any effect.

**Comment by Gimmeapill** [comment]
Confirmed as well for the Presence knob. I tried the other controls and didn't find more issues so far.

**Comment by brummer10** [comment]
Really strange. Works here as it should. 
Could you try to build the juce standalone version (make Standalone) and checkout if there is the same issue?
Just start the standalone from top source dir after build
/Builds/LinuxMakefile/build/Guitarix

Note, this version is not meant to be distributed

**Comment by kramlie** [comment]
Yes, the standalone version has the same issue.

I could try to debug it, though I would appreciate a pointer on where to start / variables to keep an eye on, since the source code is huge and I'm not super familiar with it.

**Comment by Gimmeapill** [comment]
Yes, exactly the same behavior with the standalone version.

**Comment by brummer10** [comment]
Okay, I found it. 
I could reproduce it here now as well. A fix will come with the next push, I just need to do some clean-ups.

**Comment by brummer10** [comment]
The fix is pushed to the repository. It should work now.
Additional I've implemented a File-browser for the convolvers, so that you could load now your own IR-files directly in the vst plugin.

**Comment by kramlie** [comment]
You're right, it has improved, but it still doesn't work quite right in stereo mode. It's like one side gets the update, but not the other, or something like that. Applies to both the Cabinet and Presence.

**Comment by brummer10** [comment]
Yep, forgotten the stereo mode check, it's implemented now. Thanks for keeping attention on that.

**Comment by kramlie** [comment]
Confirmed working for both controls! Thank you!!

You can close this issue as far as I'm concerned (I don't have permission).

**Comment by brummer10** [comment]
@Gimmeapill 
Do you confirm as well?

**Comment by Gimmeapill** [comment]
I do - closing
