### ISSUE TITLE
Stereo mode is not restored when loading a previously saved project

### ISSUE THREAD

**Issue by kramlie** [brummer10/guitarix.vst#8]
Title says it all, really. I switch to stereo mode, save the project, and when I load it again, it has reverted back to mono. It makes no difference whether I change it in the host or the GUI prior to saving. I'm using Ubuntu 22.04 64-bit, the host is Renoise, and I'm using commit 22dcdcf0c18d3f44bf154c0cef701e8ef5168b5d.

Otherwise really great work on this plugin! It is a huge improvement to have access to *all* the Guitarix modules!

**Comment by brummer10** [comment]
Thanks, will fix that one as well soon, but that one needs a edit in guitarix source first.

**Comment by brummer10** [comment]
Should be fixed now in latest revision. Means, new saved sessions should be able to restore the stereo/mono mode regardless if you save a preset in guitarix or save a session with your host.

**Comment by kramlie** [comment]
Unfortunately, now it crashes on startup:

```
0x00007fffd7666a44 in gx_engine::PluginList::registerGroup(PluginDef*, gx_engine::ParameterGroups&) ()
   from ~/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so
(gdb) bt
#0  0x00007fffd7666a44 in gx_engine::PluginList::registerGroup(PluginDef*, gx_engine::ParameterGroups&) ()
    at ~/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so
#1  0x00007fffd766793e in gx_engine::PluginList::registerAllPlugins(gx_engine::ParamMap&, gx_engine::ParameterGroups&) ()
    at ~/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so
#2  0x00007fffd7506310 in gx_engine::EngineControl::registerParameter(gx_engine::ParameterGroups&) ()
    at ~/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so
#3  0x00007fffd74fe25f in gx_engine::GxEngine::GxEngine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, gx_engine::ParameterGroups&, gx_system::CmdlineOptions const&) ()
    at ~/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so
#4  0x00007fffd76a4edd in gx_engine::GxMachine::GxMachine(gx_system::CmdlineOptions&) () at ~/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so
#5  0x00007fffd74ed33c in GuitarixStart::GuitarixStart(int, char**) ()
    at ~/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so
#6  0x00007fffd74ede58 in GuitarixProcessor::GuitarixProcessor() ()
    at ~/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so
#7  0x00007fffd74f2660 in createPluginFilter() ()
    at ~/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so
#8  0x00007fffd6f7d572 in  ()
```

**Comment by brummer10** [comment]
Sh*t, yes I see. That was introduced by my fix for issue #5 
Turns out that this was unstable, so I've revert that for now. 
Should work now again, including restore the stereo/mono mode, will handle issue #5 later.
regards
hermann

**Comment by kramlie** [comment]
Thanks, now it runs again. However, the original issue remains. If I save with the host, it is always back to Mono when I reload. I have not tried with the Guitarix Preset functionality.

**Comment by brummer10** [comment]
I was to fast yesterday, now it's really fixed.

**Comment by kramlie** [comment]
I can confirm, working! 👍
